version: '2'
services:
  mdeo_model_a:
    environment:
      - SOLUTION_OUTPUT
    build:
      context: ./mdeo
    command: ["sh", "-c", "cd /var/app/current && java -jar mdeo.jar 1 0 10 100 /var/app/output"]
    volumes:
          - ./mdeo/app:/var/app/current
          - ../experiments/experiment-$EXPERIMENT/mdeo/input-model-A/run-$RUN:/var/app/output/
    restart: "no"
  mdeo_model_b:
    build:
      context: ./mdeo
    command: ["sh", "-c", "cd /var/app/current && java -jar mdeo.jar 1 1 10 100 /var/app/output"]
    volumes:
          - ./mdeo/app:/var/app/current
          - ../experiments/experiment-$EXPERIMENT/mdeo/input-model-B/run-$RUN:/var/app/output/
    restart: "no"
