version: '2'
services:
  mdeo_model_a:
    environment:
      - SOLUTION_OUTPUT
    build:
      context: ./mdeo
    command: ["sh", "-c", "cd /var/app/current && java -jar mdeo.jar 1 0 10 100 /var/app/output"]
    volumes:
          - ./mdeo/app:/var/app/current
          - ../experiments/experiment-$EXPERIMENT/mdeo/input-model-a/run-$RUN:/var/app/output/
    restart: "no"
  mdeo_model_b:
    build:
      context: ./mdeo
    command: ["sh", "-c", "cd /var/app/current && java -jar mdeo.jar 1 1 10 100 /var/app/output"]
    volumes:
          - ./mdeo/app:/var/app/current
          - ../experiments/experiment-$EXPERIMENT/mdeo/input-model-b/run-$RUN:/var/app/output/
    restart: "no"
  mdeo_model_c:
    build:
      context: ./mdeo
    command: ["sh", "-c", "cd /var/app/current && java -jar mdeo.jar 1 2 10 100 /var/app/output"]
    volumes:
          - ./mdeo/app:/var/app/current
          - ../experiments/experiment-$EXPERIMENT/mdeo/input-model-c/run-$RUN:/var/app/output/
    restart: "no"
  mdeo_model_d:
    build:
      context: ./mdeo
    command: ["sh", "-c", "cd /var/app/current && java -jar mdeo.jar 1 3 10 100 /var/app/output"]
    volumes:
          - ./mdeo/app:/var/app/current
          - ../experiments/experiment-$EXPERIMENT/mdeo/input-model-d/run-$RUN:/var/app/output/
    restart: "no"
  mdeo_model_e:
    build:
      context: ./mdeo
    command: ["sh", "-c", "cd /var/app/current && java -jar mdeo.jar 1 4 10 100 /var/app/output"]
    volumes:
          - ./mdeo/app:/var/app/current
          - ../experiments/experiment-$EXPERIMENT/mdeo/input-model-e/run-$RUN:/var/app/output/
    restart: "no"