# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "puppetlabs/centos-7.0-64-puppet"

  config.vm.box_version = "1.0.2"

  config.vm.provision :shell, path: "files/scripts/setup.sh"

  # Configure hostnames using the hostupdater plugin
  config.vm.hostname = "mdebench.dev"
  config.vm.network "public_network",
                    use_dhcp_assigned_default_route: true

  #config.vm.synced_folder "../problems/", "/var/app/problems"
  config.vm.synced_folder "../../", "/var/app/mde_bench"

  # Provision the server with
  config.vm.provision :puppet do |puppet|
   # puppet.manifests_path = "puppet/manifests"
   puppet.module_path = ["provisioning/puppet/modules", "provisioning/puppet/forge_modules"]
   puppet.manifests_path = "provisioning/puppet/manifests"
   puppet.manifest_file  = "init.pp"
   puppet.options="--verbose --debug"
   puppet.environment_path="files"
  end

  config.vm.provider :virtualbox do |vb|
    vb.customize ['modifyvm', :id, '--natdnshostresolver1', 'on']
    vb.customize ['modifyvm', :id, '--natdnsproxy1', 'on']
  end
end
