Vagrant.configure(2) do |config|
  config.vm.box = "mwrock/WindowsNano"

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end
end