version: '2'
services:
  mdeo_model_a:
    environment:
      - SOLUTION_OUTPUT
    build:
      context: ./mdeo
    command: ["sh", "-c", "cd /var/app/current && java -jar mdeo.jar 1 0 10 100 /var/app/output && echo 123 > /var/app/output/time.log"]
    volumes:
          - ./mdeo/app:/var/app/current
          - ./../../experiments/experiment-$EXPERIMENT/mdeo/input-model-A/run-$RUN:/var/app/output/
    restart: "no"