version: '2'
services:
  nmf_model_a:
    environment:
      - SOLUTION_OUTPUT
    build:
      context: ./nmf
    command: ["cmd", "echo hello"]
    volumes:
          - ./nmf/app:/var/app/current
          - ../experiments/experiment-$EXPERIMENT/nmf/input-model-A/run-$RUN:/var/app/output/
    restart: "no"